### PR TITLE
New Script -  Commit Changed & Log useful  output

### PR DESCRIPTION
**Pull request by DN0000**
New script, but probably shows I'm very new to this.

Idea is to commit any pending changes, and log the output of some common commands that would be useful to refer to at a later date. Any feedback / changes welcomed & happy to let it live elsewhere if its not what your interested in!

### CODE REVIEW

**Comment by garibaldi0** [comment]
Dave,

I have a similar script that I use when doing discovery at a new customer site.  Mine does the same thing as yours, but I put the output of each command into a separate file with the format "<hostname>-<command name with underscores>-date.txt"

I think both options might be useful.  If this gets pulled in I can tweak to use an option for single or multiple files.  Or we can do two separate scripts.

**Comment by DN0000** [comment]
Merging them with an option either way would save the duplication of work

I had this one for the same situation, I was thinking of creating an index
at the start, but separate files makes more sense

Regards,
Dave Noles

---
Sent from my mobile device

On 5 Jun 2015, at 19:58, garibaldi0 <notifications@github.com> wrote:

Dave,

I have a similar script that I use when doing discovery at a new customer
site. Mine does the same thing as yours, but I put the output of each
command into a separate file with the format "--date.txt"

I think both options might be useful. If this gets pulled in I can tweak to
use an option for single or multiple files. Or we can do two separate
scripts.

—
Reply to this email directly or view it on GitHub
<https://github.com/jamiecaesar/SecureCRT/pull/4#issuecomment-109398026>.

**Comment by jamiecaesar** [comment]
Definitely interested in adding more useful scripts to the repository.  I haven't had much time to work on these or more new ones in months, so this is great.   Sorry for the delay- I got tied up earlier.  I'll try to review this later tonight or tomorrow and merge it in.

**Comment by jamiecaesar** [comment]
Dave,   Not sure if you get other notifications related to this repository, but I figure this should notify you.   I've made some additional changes to the Document_Device script, including changing the filename format (create a directory with the hostname, then saving all the files under there, with command name first, instead of hostname).   I don't feel guilty making changes to any of the scripts I wrote and put here, but I don't want to bastardize the one you added if you disagree with anything, so feel free to chime in.

**Comment by DN0000** [comment]
Hi Jamie,

Subscribed to them all - Please go ahead and update whatever you see fit,
if you seen where I am starting from if anyone is bastardising scripts it's
me!

Update away and I'll sync up. If we end up with differences, that's what
git is for.

Regards,
Dave Noles

---
Sent from my mobile device

On 11 Jun 2015, at 03:00, Jamie Caesar <notifications@github.com> wrote:

Dave, Not sure if you get other notifications related to this repository,
but I figure this should notify you. I've made some additional changes to
the Document_Device script, including changing the filename format (create
a directory with the hostname, then saving all the files under there, with
command name first, instead of hostname). I don't feel guilty making
changes to any of the scripts I wrote and put here, but I don't want to
bastardize the one you added if you disagree with anything, so feel free to
chime in.

—
Reply to this email directly or view it on GitHub
<https://github.com/jamiecaesar/SecureCRT/pull/4#issuecomment-110967928>.

**Pull request merged**
